name: Trondheimkajakk
favicon: null
layout_spectrum: 0.26352
typography_spectrum: 0.56028
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c101b'
    - '#5d6d7d'
    - '#a67f54'
    - '#ffad33'
    - '#e15732'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
