name: Trondheimkajakk
favicon: null
layout_spectrum: 0.305748782819137
typography_spectrum: 0.03085051546804607
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5882573560811579
  lightness: 0.225763953756541
  saturation: 0.36292837420478463
  rhythmicContrast: 0.6094629485160112
purpose: []
