name: Trondheimkajakk
favicon: null
layout_spectrum: 0.51006
typography_spectrum: 0.56028
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#90c3f2'
    - '#000000'
    - '#fff3d9'
    - '#ff613b'
    - '#d69f5f'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
