typography_spectrum: 0.56028
color:
  brandColors:
    - '#f4f6f5'
    - '#a6b4c1'
    - '#1b1c20'
    - '#5a6529'
    - '#f6bd66'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.89781
analytics:
  google: null
  facebook: null
  twitter: null
name: Trondheimkajakk.no
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Trondheimkajakk
purpose: []
