name: Trondheimkajakk
favicon: null
layout_spectrum: 0.61421
typography_spectrum: 0.56028
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#06050a'
    - '#c41939'
    - '#7497bf'
    - '#feb523'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
